name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  # Adjust based on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up authentication
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    # Set up gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    # Build and push the container
    - name: 'Build and Push Container'
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/rss-generator --suppress-logs
    
    # Deploy to Cloud Run
    - name: 'Deploy to Cloud Run'
      run: |
        gcloud run deploy rss-generator \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rss-generator \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
    
    # Set up Cloud Scheduler
    - name: 'Set up Cloud Scheduler'
      run: |
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe rss-generator --platform managed --region us-central1 --format 'value(status.url)')
        
        # Create or update the scheduler job
        gcloud scheduler jobs create http refresh-rss-feeds \
          --schedule="0 */12 * * *" \
          --uri="${SERVICE_URL}/refresh-all" \
          --http-method=POST \
          --attempt-deadline=540s \
          --location=us-central1 \
          --project=${{ secrets.GCP_PROJECT_ID }} || \
        gcloud scheduler jobs update http refresh-rss-feeds \
          --schedule="0 */12 * * *" \
          --uri="${SERVICE_URL}/refresh-all" \
          --http-method=POST \
          --attempt-deadline=540s \
          --location=us-central1 \
          --project=${{ secrets.GCP_PROJECT_ID }}